name: build neovim
on:
  push:
  schedule:
    - cron: '0 23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'install dependencies'
      run: 'sudo apt-get install ninja-build gettext cmake unzip curl git -y'
    - name: 'build neovim'
      run: 'bash build_neovim.sh'

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: neovim-nightly
        # path: ${{ github.workspace }}/your_dictionary
        path: /usr/local/bin/nvim
