name: build neovim
on:
  push:
  schedule:
    - cron: '0 23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'install dependencies'
      run: 'sudo apt-get install ninja-build gettext cmake unzip curl git -y'
    - name: 'build neovim'
      run: 'bash build_neovim.sh'

    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.MYTOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload release asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.MYTOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /usr/local/bin/nvim
        asset_name: neovim-nightly
        asset_content_type: application/octet-stream
