name: build neovim
on:
  push:
  schedule:
    - cron: '0 23 * * *'
jobs:
  build:
    runs-on: macos-arm64
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'install dependencies'
      run: 'brew install ninja cmake gettext curl git'
    - name: 'build neovim'
      run: 'bash build_neovim.sh'

    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: neovim-nightly
        # path: ${{ github.workspace }}/your_dictionary
        path: /usr/local/bin/nvim
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(TZ=Asia/Shanghai date +'%Y-%m-%d')"
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.MYTOKEN }}
        file: /usr/local/bin/nvim
        asset_name: neovim-nightly-${{ steps.date.outputs.date }}
        tag: ${{ github.ref }}
        overwrite: true
        body: "neovim nightly build(for nvim-ufo) ${{ steps.date.outputs.date }}"
